<?php

namespace backend\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "promoActions".
 *
 * @property int $id
 * @property string $givenByUser
 * @property string $givenByEmail
 * @property int $givenByID
 * @property string $takenByEmail
 * @property string $takenByUser
 * @property string $takenByID
 * @property string $givenByPercent
 * @property string $takenByPercent
 * @property string $condition
 * @property string|null $description
 * @property string $date
 * @property int $created_at
 * @property int $updated_at
 */
class PromoActions extends \yii\db\ActiveRecord
{
    const PROMO_CREATE_UPDATE_DELETE = 'promo_create_update_delete';

    public function init()
    {
        $this->on(self::PROMO_CREATE_UPDATE_DELETE, function ($event) {

            $promoData = array([
                'givenById' => $event->givenById,
                'takenByName' => $event->takenByName,
                'takenByEmail' => $event->takenByEmail,
            ]);

            Yii::$app->pusher->push('promo-channel-'.$event->givenById, $event->action, json_encode($promoData));
        });

        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'promoActions';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['givenByUser', 'givenByEmail', 'givenByID', 'takenByEmail', 'takenByUser', 'givenByPercent', 'takenByPercent', 'takenByID', 'condition', 'date'], 'required'],
            [['givenByID', 'takenByID', 'created_at', 'updated_at'], 'integer'],
            [['condition', 'description'], 'string'],
            [['date'], 'safe'],
            [['givenByUser', 'givenByEmail', 'takenByUser', 'takenByEmail'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'givenByUser' => 'Given By User',
            'givenByEmail' => 'Given By Email',
            'givenByID' => 'Given By ID',
            'takenByEmail' => 'Taken By Email',
            'takenByUser' => 'Taken By User',
            'givenByPercent' => 'Given By Percent',
            'takenByPercent' => 'Taken By Percent',
            'takenByID' => 'Taken By ID',
            'condition' => 'Condition',
            'description' => 'Description',
            'date' => 'Date',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
}
